///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StepsModelData {
/*
{
  "topic_id": "1",
  "topic_name": "Intro"
}
*/

  String? topicId;
  String? topicName;

  StepsModelData({
    this.topicId,
    this.topicName,
  });
  StepsModelData.fromJson(Map<String, dynamic> json) {
    topicId = json['topic_id']?.toString();
    topicName = json['topic_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['topic_id'] = topicId;
    data['topic_name'] = topicName;
    return data;
  }
}

class StepsModel {
/*
{
  "status": "success",
  "data": [
    {
      "topic_id": "1",
      "topic_name": "Intro"
    }
  ]
}
*/

  String? status;
  List<StepsModelData?>? data;

  StepsModel({
    this.status,
    this.data,
  });
  StepsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <StepsModelData>[];
      v.forEach((v) {
        arr0.add(StepsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
